### PR TITLE
Bug in sender/receiver index calculation

### PR DESCRIPTION
**Pull request by validev**

### CODE REVIEW

**Comment by mefistotelis** [comment]
I would be very surprised if the core structure of DUML had changed, or was incorrectly reverse engineered.

https://github.com/o-gs/dji-firmware-tools/blob/master/comm_dissector/wireshark/dji-dumlv1-proto.lua#L3101

Please make sure you're not misinterpreting something.
This change would have very large implications.

**Comment by validev** [comment]
fact is i cannot formulate a packet to receiver "1f". "-r 1501" translates to "2f" without my patch. I had same oddities with the sender parameter: 1001 translates to "2a". which is ok, because I need "2a", but what if i needed "1a"? Maybe I'm grossly misinterpreting sth here and the "1f" is accomplished by some other parameters I havent considered. If so, I stand corrected. Please, how would you correctly send a duml to "1f"?

**Comment by mefistotelis** [comment]
m1501 means `--receiver_type 15` and `--receiver_index 1`. In this patch, you just removed one bit from "receiver_type". Definitely not what you wanted.

**Comment by validev** [comment]
Ok, I see my error now. the data field is 5 bits, not 4. I'm sorry.

**Pull request closed without merging**
